/*
 * App template API
 *
 * API to access and configure the app template
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

import (
	"context"
	"net/http"
)

// AssetAttributeAPIRouter defines the required methods for binding the api requests to a responses for the AssetAttributeAPI
// The AssetAttributeAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AssetAttributeAPIServicer to perform the required actions, then write the service results to the http response.
type AssetAttributeAPIRouter interface {
	DeleteAssetAttributes(http.ResponseWriter, *http.Request)
	GetAssetAttributes(http.ResponseWriter, *http.Request)
	PutAssetAttribute(http.ResponseWriter, *http.Request)
}

// ConfigurationAPIRouter defines the required methods for binding the api requests to a responses for the ConfigurationAPI
// The ConfigurationAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ConfigurationAPIServicer to perform the required actions, then write the service results to the http response.
type ConfigurationAPIRouter interface {
	DeleteConfigurationById(http.ResponseWriter, *http.Request)
	GetConfigurationById(http.ResponseWriter, *http.Request)
	GetConfigurations(http.ResponseWriter, *http.Request)
	PostConfiguration(http.ResponseWriter, *http.Request)
	PutConfigurationById(http.ResponseWriter, *http.Request)
}

// VersionAPIRouter defines the required methods for binding the api requests to a responses for the VersionAPI
// The VersionAPIRouter implementation should parse necessary information from the http request,
// pass the data to a VersionAPIServicer to perform the required actions, then write the service results to the http response.
type VersionAPIRouter interface {
	GetOpenAPI(http.ResponseWriter, *http.Request)
	GetVersion(http.ResponseWriter, *http.Request)
}

// AssetAttributeAPIServicer defines the api actions for the AssetAttributeAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AssetAttributeAPIServicer interface {
	DeleteAssetAttributes(context.Context, int32, int32, string, string) (ImplResponse, error)
	GetAssetAttributes(context.Context, int32, int32, string, string) (ImplResponse, error)
	PutAssetAttribute(context.Context, AssetAttribute) (ImplResponse, error)
}

// ConfigurationAPIServicer defines the api actions for the ConfigurationAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ConfigurationAPIServicer interface {
	DeleteConfigurationById(context.Context, int64) (ImplResponse, error)
	GetConfigurationById(context.Context, int64) (ImplResponse, error)
	GetConfigurations(context.Context) (ImplResponse, error)
	PostConfiguration(context.Context, Configuration) (ImplResponse, error)
	PutConfigurationById(context.Context, int64, Configuration) (ImplResponse, error)
}

// VersionAPIServicer defines the api actions for the VersionAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type VersionAPIServicer interface {
	GetOpenAPI(context.Context) (ImplResponse, error)
	GetVersion(context.Context) (ImplResponse, error)
}
