// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package appdb

var TableNames = struct {
	AssetAttribute string
	Configuration  string
}{
	AssetAttribute: "asset_attribute",
	Configuration:  "configuration",
}
